pfcount: Add missing includes to declare trace()
pfcount.c:128:2: error: implicit declaration of function 'trace' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        trace("passcount=%d, failcount=%d", passcount, failcount);
        ^
1 error generated.

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>