XInput: Add missing includes for report() declaration
XInput.c:172:9: error: implicit declaration of function 'report' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        report("DISPLAY is not set.  Cannot continue");
        ^

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>