bitcount: Add missing include for debug() prototype
bitcount.c:192:2: error: implicit declaration of function 'debug' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        debug(1, "getpix: Pixel is %lx from %lx and %lx.", pix, m, p);
        ^
1 error generated.

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>