settimeout: Add missing include for delete() prototype
settimeout.c:154:3: error: implicit declaration of function 'delete' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                delete("Could not set signal handler in settimeout");
                ^
settimeout.c:154:3: note: did you mean 'undelete'?
/Library/Developer/CommandLineTools/SDKs/MacOSX13.2.sdk/usr/include/unistd.h:737:6: note: 'undelete' declared here
int      undelete(const char *);
         ^
settimeout.c:175:3: error: implicit declaration of function 'delete' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                delete("Could not reset signal handler in cleartimeout");
                ^
2 errors generated.

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>